sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '6'
  - '8'
  - '10'
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
